# Generated by Django 4.0.6 on 2023-01-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='produc',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
