# Generated by Django 4.0.6 on 2023-01-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_produc_image_product_remove_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
